# TCL File Generated by Component Editor 26.1
# Mon Aug 10 12:07:59 CST 2026
# DO NOT MODIFY


# 
# nios_iopll_bridge "Nios IOPLL Bridge" v1.0
# jiayao 2026.08.10.12:07:59
# Avalon-MM bridge for Nios V control of Agilex 5 IOPLL HVIO reconfiguration.
# 

# 
# request TCL package from ACDS 26.1
# 
package require -exact qsys 26.1


# 
# module nios_iopll_bridge
# 
set_module_property DESCRIPTION "Avalon-MM bridge for Nios V control of Agilex 5 IOPLL HVIO reconfiguration."
set_module_property NAME nios_iopll_bridge
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property BSP_CPU false
set_module_property GROUP "Custom Instruction Modules"
set_module_property AUTHOR jiayao
set_module_property DISPLAY_NAME "Nios IOPLL Bridge"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0
set_module_property PRE_COMP_MODULE_ENABLED false
set_module_property DISPLAY_ICON ""


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL nios_iopll_bridge
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file nios_iopll_bridge.sv SYSTEM_VERILOG PATH rtl/nios_iopll_bridge.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""
set_interface_property clock IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property clock SV_INTERFACE_TYPE ""
set_interface_property clock SV_INTERFACE_MODPORT_TYPE ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""
set_interface_property reset IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property reset SV_INTERFACE_TYPE ""
set_interface_property reset SV_INTERFACE_MODPORT_TYPE ""

add_interface_port reset rst_n reset_n Input 1


# 
# connection point avs
# 
add_interface avs avalon end
set_interface_property avs addressGroup 0
set_interface_property avs addressUnits WORDS
set_interface_property avs associatedClock clock
set_interface_property avs associatedReset reset
set_interface_property avs bitsPerSymbol 8
set_interface_property avs bridgedAddressOffset ""
set_interface_property avs bridgesToMaster ""
set_interface_property avs burstOnBurstBoundariesOnly false
set_interface_property avs burstcountUnits WORDS
set_interface_property avs explicitAddressSpan 0
set_interface_property avs holdTime 0
set_interface_property avs linewrapBursts false
set_interface_property avs maximumPendingReadTransactions 0
set_interface_property avs maximumPendingWriteTransactions 0
set_interface_property avs minimumResponseLatency 1
set_interface_property avs readLatency 0
set_interface_property avs readWaitTime 1
set_interface_property avs setupTime 0
set_interface_property avs timingUnits Cycles
set_interface_property avs transparentBridge false
set_interface_property avs waitrequestAllowance 0
set_interface_property avs writeWaitTime 0
set_interface_property avs dfhFeatureGuid 0
set_interface_property avs dfhGroupId 0
set_interface_property avs dfhParameterId ""
set_interface_property avs dfhParameterName ""
set_interface_property avs dfhParameterVersion ""
set_interface_property avs dfhParameterData ""
set_interface_property avs dfhParameterDataLength ""
set_interface_property avs dfhFeatureMajorVersion 0
set_interface_property avs dfhFeatureMinorVersion 0
set_interface_property avs dfhFeatureId 35
set_interface_property avs dfhFeatureType 3
set_interface_property avs ENABLED true
set_interface_property avs EXPORT_OF ""
set_interface_property avs PORT_NAME_MAP ""
set_interface_property avs CMSIS_SVD_VARIABLES ""
set_interface_property avs SVD_ADDRESS_GROUP ""
set_interface_property avs IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property avs SV_INTERFACE_TYPE ""
set_interface_property avs SV_INTERFACE_MODPORT_TYPE ""

add_interface_port avs avs_address address Input 3
add_interface_port avs avs_read read Input 1
add_interface_port avs avs_write write Input 1
add_interface_port avs avs_writedata writedata Input 32
add_interface_port avs avs_readdata readdata Output 32
add_interface_port avs avs_waitrequest waitrequest Output 1
set_interface_assignment avs embeddedsw.configuration.isFlash 0
set_interface_assignment avs embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avs embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avs embeddedsw.configuration.isPrintableDevice 0


# 
# connection point iopll_cmd
# 
add_interface iopll_cmd conduit end
set_interface_property iopll_cmd associatedClock clock
set_interface_property iopll_cmd associatedReset ""
set_interface_property iopll_cmd ENABLED true
set_interface_property iopll_cmd EXPORT_OF ""
set_interface_property iopll_cmd PORT_NAME_MAP ""
set_interface_property iopll_cmd CMSIS_SVD_VARIABLES ""
set_interface_property iopll_cmd SVD_ADDRESS_GROUP ""
set_interface_property iopll_cmd IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property iopll_cmd SV_INTERFACE_TYPE ""
set_interface_property iopll_cmd SV_INTERFACE_MODPORT_TYPE ""

add_interface_port iopll_cmd cmd_start cmd_start Output 1
add_interface_port iopll_cmd cmd_write cmd_write Output 1
add_interface_port iopll_cmd cmd_address cmd_address Output 9
add_interface_port iopll_cmd cmd_writedata cmd_writedata Output 32
add_interface_port iopll_cmd cmd_readdata cmd_readdata Input 32
add_interface_port iopll_cmd cmd_busy cmd_busy Input 1
add_interface_port iopll_cmd cmd_done cmd_done Input 1
add_interface_port iopll_cmd cmd_error cmd_error Input 1
add_interface_port iopll_cmd pll_locked_async pll_locked_async Input 1
add_interface_port iopll_cmd diagnostic_software_reset diagnostic_software_reset Output 1
