// system_nios_iopll_bridge_0.v

// Generated using ACDS version 26.1 110

`timescale 1 ps / 1 ps
module system_nios_iopll_bridge_0 (
		input  wire        clk,                       //     clock.clk
		input  wire        rst_n,                     //     reset.reset_n
		input  wire [2:0]  avs_address,               //       avs.address
		input  wire        avs_read,                  //          .read
		input  wire        avs_write,                 //          .write
		input  wire [31:0] avs_writedata,             //          .writedata
		output wire [31:0] avs_readdata,              //          .readdata
		output wire        avs_waitrequest,           //          .waitrequest
		output wire        cmd_start,                 // iopll_cmd.cmd_start
		output wire        cmd_write,                 //          .cmd_write
		output wire [8:0]  cmd_address,               //          .cmd_address
		output wire [31:0] cmd_writedata,             //          .cmd_writedata
		input  wire [31:0] cmd_readdata,              //          .cmd_readdata
		input  wire        cmd_busy,                  //          .cmd_busy
		input  wire        cmd_done,                  //          .cmd_done
		input  wire        cmd_error,                 //          .cmd_error
		input  wire        pll_locked_async,          //          .pll_locked_async
		output wire        diagnostic_software_reset  //          .diagnostic_software_reset
	);

	nios_iopll_bridge nios_iopll_bridge_0 (
		.clk                       (clk),                       //   input,   width = 1,     clock.clk
		.rst_n                     (rst_n),                     //   input,   width = 1,     reset.reset_n
		.avs_address               (avs_address),               //   input,   width = 3,       avs.address
		.avs_read                  (avs_read),                  //   input,   width = 1,          .read
		.avs_write                 (avs_write),                 //   input,   width = 1,          .write
		.avs_writedata             (avs_writedata),             //   input,  width = 32,          .writedata
		.avs_readdata              (avs_readdata),              //  output,  width = 32,          .readdata
		.avs_waitrequest           (avs_waitrequest),           //  output,   width = 1,          .waitrequest
		.cmd_start                 (cmd_start),                 //  output,   width = 1, iopll_cmd.cmd_start
		.cmd_write                 (cmd_write),                 //  output,   width = 1,          .cmd_write
		.cmd_address               (cmd_address),               //  output,   width = 9,          .cmd_address
		.cmd_writedata             (cmd_writedata),             //  output,  width = 32,          .cmd_writedata
		.cmd_readdata              (cmd_readdata),              //   input,  width = 32,          .cmd_readdata
		.cmd_busy                  (cmd_busy),                  //   input,   width = 1,          .cmd_busy
		.cmd_done                  (cmd_done),                  //   input,   width = 1,          .cmd_done
		.cmd_error                 (cmd_error),                 //   input,   width = 1,          .cmd_error
		.pll_locked_async          (pll_locked_async),          //   input,   width = 1,          .pll_locked_async
		.diagnostic_software_reset (diagnostic_software_reset)  //  output,   width = 1,          .diagnostic_software_reset
	);

endmodule
